# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: acifani/setup-tinygo@v2.0.0
      with:
        tinygo-version: 0.37.0
        install-binaryen: true
        binaryen-version: 123
    - name: Build
      run: tinygo build -o raycasting.wasm -target wasm .
    - name: Upload WASM
      uses: actions/upload-artifact@v4
      with:
        name: raycasting.wasm
        path: raycasting.wasm
